dist: trusty
sudo: false
language: cpp
notifications:
  email: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      compiler: g++-7

script:
  - cmake --version
  - ${CXX} --version
  - mkdir build && cd build
  - CXX=${CXX} cmake -GNinja ..
  - ninja
