dist: trusty
sudo: false
language: cpp
notifications:
  email: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-test-dev
            - ninja-build
      env:
         - CXX=g++-7
    - os: linux
      addons:
        apt:
          packages:
            - libboost-test-dev
            - libboost-dev
            - ninja-build
      env:
         - CXX=clang++

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - ${CXX} --version
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
