dist: trusty
sudo: false
language: cpp
notifications:
  email: false
cache:
  directories:
    - download

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env:
        - MATRIX_EVAL="CXX=g++-7"
        - CXX=g++-7
    - os: linux
      addons:
        apt:
          packages:
            - ninja-build
      env:
        - MATRIX_EVAL="CXX=clang++"
        - CXX=clang++

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - cp helper/getboost.sh .
  - ./getboost.sh
  - tar xzf download/boost_1_59_0.tar.gz
  - cp helper/buildboost.sh boost_1_59_0/
  - cd boost_1_59_0/
  - ./bootstrap.sh --prefix=/usr/local
  - CXX=${CXX} ./buildboost.sh
  - sudo ./b2 install -d0

script:
  - eval "${MATRIX_EVAL}"
  - cmake --version
  - ${CXX} --version
  - mkdir build && cd build
  - CXX=${CXX} cmake -GNinja ..
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
  - ninja test
