language: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-all-dev
            - ninja-build
      env:
         - MATRIX_EVAL="CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
  - ninja test
