dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-test-dev
            - ninja-build
      env:
         - MATRIX_EVAL="CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
  - ninja test
